// ─── State Constants ────────────────────────────────────────────
// Transaction state machine values from ARCHITECTURE.md.

export const STATES = {
  PROPOSED: 'PROPOSED',
  VALIDATED: 'VALIDATED',
  BLOCKED: 'BLOCKED',
  EXECUTING: 'EXECUTING',
  EXECUTION_UNKNOWN: 'EXECUTION_UNKNOWN',
  VERIFYING: 'VERIFYING',
  RETRY_ELIGIBLE: 'RETRY_ELIGIBLE',
  VERIFIED_SUCCESS: 'VERIFIED_SUCCESS',
  VERIFIED_FAILURE: 'VERIFIED_FAILURE',
  ESCALATED: 'ESCALATED',
} as const;

export type State = (typeof STATES)[keyof typeof STATES];

/** Valid state transitions */
export const STATE_TRANSITIONS: Record<string, string[]> = {
  [STATES.PROPOSED]: [STATES.VALIDATED, STATES.ESCALATED],
  [STATES.VALIDATED]: [STATES.BLOCKED, STATES.EXECUTING, STATES.ESCALATED],
  [STATES.EXECUTING]: [
    STATES.EXECUTION_UNKNOWN,
    STATES.VERIFIED_SUCCESS,
    STATES.VERIFIED_FAILURE,
  ],
  [STATES.EXECUTION_UNKNOWN]: [STATES.VERIFYING],
  [STATES.VERIFYING]: [
    STATES.VERIFIED_SUCCESS,
    STATES.VERIFIED_FAILURE,
    STATES.ESCALATED,
  ],
  [STATES.VERIFIED_FAILURE]: [STATES.RETRY_ELIGIBLE],
  [STATES.RETRY_ELIGIBLE]: [STATES.EXECUTING],
};

/** Check if a state transition is valid */
export function isValidTransition(from: string, to: string): boolean {
  const allowed = STATE_TRANSITIONS[from];
  return allowed ? allowed.includes(to) : false;
}

// ─── Agent States ───────────────────────────────────────────────

export const AGENT_STATES = {
  NEW: 'NEW',
  DISCOVERING: 'DISCOVERING',
  COMPARING: 'COMPARING',
  NEGOTIATING: 'NEGOTIATING',
  WAITING_POLICY: 'WAITING_POLICY',
  POLICY_REJECTED: 'POLICY_REJECTED',
  ADAPTING: 'ADAPTING',
  READY_FOR_CHECKOUT: 'READY_FOR_CHECKOUT',
  EXECUTING: 'EXECUTING',
  EXECUTION_UNKNOWN: 'EXECUTION_UNKNOWN',
  VERIFYING: 'VERIFYING',
  COMPLETED: 'COMPLETED',
  ESCALATED: 'ESCALATED',
  FAILED: 'FAILED',
} as const;

export type AgentState = (typeof AGENT_STATES)[keyof typeof AGENT_STATES];

export const AGENT_STATE_TRANSITIONS: Record<string, string[]> = {
  [AGENT_STATES.NEW]: [AGENT_STATES.DISCOVERING],
  [AGENT_STATES.DISCOVERING]: [AGENT_STATES.COMPARING, AGENT_STATES.ESCALATED, AGENT_STATES.FAILED],
  [AGENT_STATES.COMPARING]: [AGENT_STATES.NEGOTIATING, AGENT_STATES.ESCALATED, AGENT_STATES.FAILED],
  [AGENT_STATES.NEGOTIATING]: [AGENT_STATES.WAITING_POLICY, AGENT_STATES.ESCALATED, AGENT_STATES.FAILED],
  [AGENT_STATES.WAITING_POLICY]: [AGENT_STATES.READY_FOR_CHECKOUT, AGENT_STATES.POLICY_REJECTED, AGENT_STATES.ESCALATED, AGENT_STATES.FAILED],
  [AGENT_STATES.POLICY_REJECTED]: [AGENT_STATES.ADAPTING, AGENT_STATES.ESCALATED, AGENT_STATES.FAILED],
  [AGENT_STATES.ADAPTING]: [AGENT_STATES.WAITING_POLICY, AGENT_STATES.ESCALATED, AGENT_STATES.FAILED],
  [AGENT_STATES.READY_FOR_CHECKOUT]: [AGENT_STATES.EXECUTING, AGENT_STATES.ESCALATED, AGENT_STATES.FAILED],
  [AGENT_STATES.EXECUTING]: [AGENT_STATES.EXECUTION_UNKNOWN, AGENT_STATES.VERIFYING, AGENT_STATES.COMPLETED, AGENT_STATES.FAILED],
  [AGENT_STATES.EXECUTION_UNKNOWN]: [AGENT_STATES.VERIFYING],
  [AGENT_STATES.VERIFYING]: [AGENT_STATES.COMPLETED, AGENT_STATES.FAILED, AGENT_STATES.ESCALATED],
  [AGENT_STATES.COMPLETED]: [],
  [AGENT_STATES.ESCALATED]: [],
  [AGENT_STATES.FAILED]: [],
};

export function isValidAgentTransition(from: string, to: string): boolean {
  const allowed = AGENT_STATE_TRANSITIONS[from];
  return allowed ? allowed.includes(to) : false;
}
